import pandas as pd
import matplotlib.pyplot as plt
import re
import os

# === Log files and labels ===
# Resolve path relative to this script directory (portable)
base_dir = os.path.dirname(os.path.abspath(__file__))
logs_dir = os.path.join(base_dir, "logs")

log_files = [
    os.path.join(logs_dir, "log_mrac_teste3.csv")
]

labels = [
    "MRAC"
]

# === Variables present in the CSV generated by the logging script ===
all_variables = [
    "t", "v_ref", "w_ref", "v", "w",
    "omega_L", "omega_R", "u_L", "u_R",
    "w_L", "w_R",
    "theta1_L", "theta2_L", "theta1_R", "theta2_R",
    "e_L", "e_R"
]

# === Variables to be plotted ===
# Omegas juntos em uma única figura com referências
variables_to_plot = ["omega_LR"]

# === Colors for the curves ===
colors = ['tab:blue', 'tab:orange', 'tab:green', 'tab:red', 'tab:purple', 'tab:brown']

plots_dir = os.path.join(base_dir, "plots_teste3")
os.makedirs(plots_dir, exist_ok=True)

for idx, (file, label) in enumerate(zip(log_files, labels)):
    if not os.path.exists(file):
        print(f"[!] File not found: {file}")
        continue

    try:
        df = pd.read_csv(file)
        df["t"] = df["t"] / 1_000_000  # convert microseconds to seconds
        df["t"] = df["t"] - df["t"].iloc[0] + 0.1  # start at 0.1s
    except Exception as e:
        print(f"[!] Error reading {file}: {e}")
        continue

    # Gerar figura com ambos omegas e referências
    fig, ax = plt.subplots(figsize=(7, 3))

    # Plot omega_L e omega_R
    if "omega_L" in df.columns:
        ax.plot(df["t"], df["omega_L"], label=r"$\omega_L$ medido", color=colors[0])
    if "omega_R" in df.columns:
        ax.plot(df["t"], df["omega_R"], label=r"$\omega_R$ medido", color=colors[1])
    
    # Plot referência única (u_L = u_R)
    if "u_L" in df.columns:
        ax.plot(df["t"], df["u_L"], "--", color="black", label="Referência")

    ax.set_xlabel("Tempo [s]")
    ax.set_ylabel(r"$\omega$ (rad/s)")
    ax.grid(True)
    ax.legend()
    fig.tight_layout()
    
    plt.show()

    out_name = "omega_LR.pdf"
    out_path = os.path.join(plots_dir, out_name)
    try:
        fig.savefig(out_path, format="pdf")
        print(f"[+] Figura salva: {out_path}")
    except Exception as e:
        print(f"[!] Erro ao salvar {out_path}: {e}")
    plt.close(fig)

print(f"[+] Concluído. Figuras geradas em: {plots_dir}")
