import pandas as pd
import matplotlib.pyplot as plt
import re
import os

# === Log files and labels ===
# Resolve path relative to this script directory (portable)
base_dir = os.path.dirname(os.path.abspath(__file__))
logs_dir = os.path.join(base_dir, "logs")

log_files = [
    os.path.join(logs_dir, "log_mrac_teste2_fixed.csv")
]

labels = [
    "MRAC"
]

# === Variables present in the CSV generated by the logging script ===
all_variables = [
    "t", "v_ref", "w_ref", "v", "w",
    "omega_L", "omega_R", "u_L", "u_R",
    "w_L", "w_R",
    "theta1_L", "theta2_L", "theta1_R", "theta2_R",
    "e_L", "e_R"
]

# === Variables to be plotted ===
# Agrupamos u_L com omega_L e u_R com omega_R (u_* é referência)
# u_L e u_R mostram ações de controle (PWM).
variables_to_plot = ["omega_L", "omega_R", "u_L", "u_R"]

# === Colors for the curves ===
colors = ['tab:blue', 'tab:orange', 'tab:green', 'tab:red', 'tab:purple', 'tab:brown']

plots_dir = os.path.join(base_dir, "plots_teste2")
os.makedirs(plots_dir, exist_ok=True)

for idx, (file, label) in enumerate(zip(log_files, labels)):
    if not os.path.exists(file):
        print(f"[!] File not found: {file}")
        continue

    try:
        df = pd.read_csv(file)
        df["t"] = df["t"] / 1_000_000  # convert microseconds to seconds
        df["t"] = df["t"] - df["t"].iloc[0] + 0.1  # start at 0.1s
    except Exception as e:
        print(f"[!] Error reading {file}: {e}")
        continue

    # Para cada variável gerar figura individual
    for var in variables_to_plot:
        if var not in df.columns:
            print(f"[!] Variable '{var}' not found in {file}")
            continue

        fig, ax = plt.subplots(figsize=(7, 3))

        # Plot principal + referências conforme solicitado
        if var == "omega_L":
            ax.plot(df["t"], df[var], label=r"$\omega_L$ medido", color=colors[idx % len(colors)])
            if "u_L" in df.columns:
                ax.plot(df["t"], df["u_L"], "--", color="black", label="Referência")
            ax.set_ylabel(r"$\omega_L$ (rad/s)")
        elif var == "omega_R":
            ax.plot(df["t"], df[var], label=r"$\omega_R$ medido", color='tab:orange')
            if "u_R" in df.columns:
                ax.plot(df["t"], df["u_R"], "--", color="black", label="Referência")
            ax.set_ylabel(r"$\omega_R$ (rad/s)")
        elif var == "u_L":
            ax.plot(df["t"], df[var], color=colors[idx % len(colors)])
            ax.set_ylabel(r"$u_L$ (PWM)")
        elif var == "u_R":
            ax.plot(df["t"], df[var], color=colors[idx % len(colors)])
            ax.set_ylabel(r"$u_R$ (PWM)")
        elif var == "w_R":
            ax.plot(df["t"], df[var], label="w_R", color=colors[idx % len(colors)])
            ax.set_ylabel("w_R")
        elif var == "v":
            ax.plot(df["t"], df[var], label="v medido", color=colors[idx % len(colors)])
            if "v_ref" in df.columns:
                ax.plot(df["t"], df["v_ref"], "--", color="black", label="v referência")
            ax.set_ylabel("v (m/s)")
        elif var == "w":
            ax.plot(df["t"], df[var], label=r"$\omega$ medido", color=colors[idx % len(colors)])
            if "w_ref" in df.columns:
                ax.plot(df["t"], df["w_ref"], "--", color="black", label=r"$\omega$ referência")
            ax.set_ylabel(r"$\omega$ (rad/s)")
        else:
            ax.plot(df["t"], df[var], label=f"{label} {var}", color=colors[idx % len(colors)])
            ax.set_ylabel(var)

        ax.set_xlabel("Tempo [s]")
        ax.grid(True)
        if var not in ["u_L", "u_R"]:
            ax.legend()
        fig.tight_layout()

        plt.show()

        out_name = f"{var}.pdf"
        out_path = os.path.join(plots_dir, out_name)
        try:
            fig.savefig(out_path, format="pdf")
            print(f"[+] Figura salva: {out_path}")
        except Exception as e:
            print(f"[!] Erro ao salvar {out_path}: {e}")
        plt.close(fig)

print(f"[+] Concluído. Figuras geradas em: {plots_dir}")
