import pandas as pd
import matplotlib.pyplot as plt
import re
import os

# === Log files and labels ===
# Resolve path relative to this script directory (portable)
base_dir = os.path.dirname(os.path.abspath(__file__))
logs_dir = os.path.join(base_dir, "logs")

log_files = [
    os.path.join(logs_dir, "log_mrac_2.csv")
]

labels = [
    "MRAC"
]

# === Variables present in the CSV generated by the logging script ===
all_variables = [
    "t", "v_ref", "w_ref", "v", "w",
    "omega_L", "omega_R", "u_L", "u_R",
    "w_L", "w_R",
    "theta1_L", "theta2_L", "theta1_R", "theta2_R",
    "e_L", "e_R"
]

# === Variables to be plotted ===
variables_to_plot = ["omega_L", "omega_R", "w_L", "w_R",]

# === Colors for the curves ===
colors = ['tab:blue', 'tab:orange', 'tab:green', 'tab:red', 'tab:purple', 'tab:brown']

# === Create subplots ===
fig, axs = plt.subplots(len(variables_to_plot), 1, figsize=(10, 3 * len(variables_to_plot)), sharex=True)
fig.subplots_adjust(hspace=0.4)
if len(variables_to_plot) == 1:
    axs = [axs]  # Ensure axs is always a list even for a single subplot

for idx, (file, label) in enumerate(zip(log_files, labels)):
    if not os.path.exists(file):
        print(f"[!] File not found: {file}")
        continue

    try:
        df = pd.read_csv(file)
        df["t"] = df["t"] / 1_000_000  # convert microseconds to seconds
    except Exception as e:
        print(f"[!] Error reading {file}: {e}")
        continue

    for i, var in enumerate(variables_to_plot):
        if var not in df.columns:
            print(f"[!] Variable '{var}' not found in {file}")
            continue

        # Plot main variable with proper labels
        if var == "v":
            axs[i].plot(df["t"], df[var], label="v medido", color=colors[idx % len(colors)])
        elif var == "w":
            axs[i].plot(df["t"], df[var], label=r"$\omega$ medido", color=colors[idx % len(colors)])
        else:
            axs[i].plot(df["t"], df[var], label=f"{label} {var}", color=colors[idx % len(colors)])

        # Add v_ref to the same subplot as v, dashed line
        if var == "v" and "v_ref" in df.columns:
            axs[i].plot(df["t"], df["v_ref"], "--", color="black", label="v referência")

        # Add w_ref to the same subplot as w, dashed line
        if var == "w" and "w_ref" in df.columns:
            axs[i].plot(df["t"], df["w_ref"], "--", color="black", label=r"$\omega$ referência")

# === Aesthetics for the plots ===
for i, var in enumerate(variables_to_plot):
    if var == "v":
        axs[i].set_ylabel("v (m/s)")
    elif var == "w":
        axs[i].set_ylabel(r"$\omega$ (rad/s)")
    else:
        axs[i].set_ylabel(var)
    axs[i].grid(True)
    axs[i].legend()

axs[-1].set_xlabel("Tempo [s]")
# fig.suptitle("Identificação do sistema caixa cinza", fontsize=14)
plt.tight_layout(rect=[0, 0, 1, 0.96])
plt.show()
